### ISSUE TITLE
Black Ui View on running

### ISSUE THREAD

**Issue by alisattar456** [iDevelopper/PBRevealViewController#11]
![screen shot 2016-10-14 at 11 38 51 am](https://cloud.githubusercontent.com/assets/18255723/19398836/5a918f52-9203-11e6-9bbf-01842c9c421c.png)
![screen shot 2016-10-14 at 11 39 15 am](https://cloud.githubusercontent.com/assets/18255723/19398835/5a8cb4a0-9203-11e6-904f-035fb4e2c451.png)
![Uploading Screen Shot 2016-10-14 at 11.39.28 AM.png…]()
![screen shot 2016-10-14 at 11 40 15 am](https://cloud.githubusercontent.com/assets/18255723/19398838/5aa393fa-9203-11e6-9a8b-796461e4d3c7.png)
![Uploading Screen Shot 2016-10-14 at 11.40.42 AM.png…]()

**Comment by Sebacho-Barajas** [comment]
did you add pbrevealviewcontroller as initial view controller
![screen shot 2016-10-14 at 3 10 15 pm](https://cloud.githubusercontent.com/assets/10381993/19399708/da3aea60-9220-11e6-99de-9013d2280187.png)
?

and did you set the (pb_main and pb_left)segues as `PBRevealViewControllerSegueSetController`

and in the home view controller you should set it like this 
viewDidload  

```
_sidebarButton.target = self.revealViewController;
_sidebarButton.action = @selector(revealLeftView);
```

you don't need to add panGestureRecognizer as pbrevealviewcontroller adds it automatically

**Comment by iDevelopper** [comment]
As @Sebacho-Barajas wrote:

Your storyboard segue have to be like this (I think you've selected PBRevealViewControllerSeguePushController):

![2016-10-15_06-50-39](https://cloud.githubusercontent.com/assets/1782450/19407493/cd4e5584-92a3-11e6-8f57-05920a598f3d.png)

Same for pb_left.

**Comment by alisattar456** [comment]
#11
