### ISSUE TITLE
can i use self.revealViewController.leftPresentViewHierarchically = YES; in UIView instead of Navigation UView

### ISSUE THREAD

**Issue by alisattar456** [iDevelopper/PBRevealViewController#12]

**Comment by iDevelopper** [comment]
Can you be more explicit, please?

**Comment by alisattar456** [comment]
![screen shot 2016-10-15 at 4 01 27 am](https://cloud.githubusercontent.com/assets/18255723/19409603/39e90d78-928c-11e6-8403-ac8526dc47f1.png)
I am Creating View like this but i don't want to use navigation bar I use simple view and want to bring view front just like navigation view
![screen shot 2016-10-15 at 4 00 23 am](https://cloud.githubusercontent.com/assets/18255723/19409613/7f57313c-928c-11e6-9f07-1b8b89040362.png)
bring view to front 
![screen shot 2016-10-15 at 4 00 49 am](https://cloud.githubusercontent.com/assets/18255723/19409616/916505e8-928c-11e6-8c77-506e493fe8e1.png)

**Comment by alisattar456** [comment]
i am working on this creating same layout design
![14627812_750646321741201_745533865_n](https://cloud.githubusercontent.com/assets/18255723/19409634/096c17ca-928d-11e6-9f07-740bc1ccafc0.png)

**Comment by iDevelopper** [comment]
Embed the left view controller in a navigation controller and uncheck Shows Navigation Bar:

![2016-10-15_13-46-00](https://cloud.githubusercontent.com/assets/1782450/19409856/d74685e0-92dd-11e6-8431-eedf1c4bc3f4.png)

This is a sample:

[PBRevealSample.zip](https://github.com/iDevelopper/PBRevealViewController/files/531110/PBRevealSample.zip)

**Comment by alisattar456** [comment]
Thanks  Sir Enjoying Your Company
