### ISSUE TITLE
i want to change button image when reveal view controller appears as shown in  image 

### ISSUE THREAD

**Issue by alisattar456** [iDevelopper/PBRevealViewController#13]
![14627812_750646321741201_745533865_n](https://cloud.githubusercontent.com/assets/18255723/19410045/cd589470-9296-11e6-960c-4dd5ca7eddd1.jpeg)

**Comment by iDevelopper** [comment]
Sorry for late answer! Did you solve it?

**Comment by alisattar456** [comment]
No waiting for your reply and doing some other work now tell me?

**Comment by iDevelopper** [comment]
Sorry again, you have to use the delegate methods willShowLeftViewController & willShowHideViewController, this sample written in Swift but very easy to understand:

[PBNavSample.zip](https://github.com/iDevelopper/PBRevealViewController/files/578987/PBNavSample.zip)

**Comment by alisattar456** [comment]
ok no Problem thats fine

**Comment by alisattar456** [comment]
PBrevealViewController touch gesture is not working on webview

**Comment by alisattar456** [comment]
in objective c

**Comment by iDevelopper** [comment]
Please open an other issue
