### ISSUE TITLE
self.revealViewController().delegate is nil?

### ISSUE THREAD

**Issue by Dbigshooter** [iDevelopper/PBRevealViewController#14]
Hi there,

In one of my viewControllers I use it with success, however I'm facing a problem in a viewController where I want the leftView to be called from a button. Whenever I try to set the delegate with self.revealViewController().delegate = self it fails at runtime caused by a nil. In my class I basically do this:

```
class MapViewController: UIViewController, PBRevealViewControllerDelegate {
...
    @IBOutlet weak var menuButton: UIButton!
...
override func viewDidLoad() {
        super.viewDidLoad()
...
        self.revealViewController().delegate = self
...
menuButton.addTarget(self, action: #selector(self.revealLeftView), for: UIControlEvents.touchUpInside)
...
}
```

The self.revealLeftView basically just call the revealLeftView on the PBRevealViewController. I got my main view set up with pb_main and the menu view with pb_left. 

![pbrevealview](https://cloud.githubusercontent.com/assets/6803648/20039978/e0259bec-a44e-11e6-8403-b78397321d47.png)

If I leave out the delegate setting the menu works fine, but I can't customize it. Should I place the delegate in the ViewDidAppear instead?

**Comment by iDevelopper** [comment]
Hi @Dbigshooter , my fault. Fixed and pushed to Github and CocoaPods (version 1.1.1).

**Comment by Dbigshooter** [comment]
@iDevelopper Thanks! I'm facing another problem now, in my menu, shown above, I get a nil why I try to do this:

`let navController = self.revealViewController().mainViewController as? UINavigationController`
