### ISSUE TITLE
Navigation back through navigation controllers?

### ISSUE THREAD

**Issue by Dbigshooter** [iDevelopper/PBRevealViewController#15]
Hi there,

I want to navigate back to another specific viewcontroller, but can't figure out how this is done, especially not when PBRevealViewController is in there. I've tried to draw what I want, any help will be greatly appreciated!

![pbrevealviewcontrollernavigation](https://cloud.githubusercontent.com/assets/6803648/20065355/1a38b066-a50e-11e6-9217-5e0f611fd006.png)

**Comment by iDevelopper** [comment]
It is very difficult to read as the image is blurred. But I think you have to save somewhere a reference to the first reveal view controller.

**Comment by Dbigshooter** [comment]
@iDevelopper Thanks for the quick response! How would you do that?

**Comment by iDevelopper** [comment]
You could declare a variable in AppDelegate and save to it the first revealViewController then you can retrieve it from anywhere.

**Comment by iDevelopper** [comment]
Sample:

[PBTwoRevealVC.zip](https://github.com/iDevelopper/PBRevealViewController/files/577629/PBTwoRevealVC.zip)
