### ISSUE TITLE
I want to Move xib to pbrevealView Controller 

### ISSUE THREAD

**Issue by alisattar456** [iDevelopper/PBRevealViewController#16]
UIStoryboard *storyBoard = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
    PBRevealViewController *Object;
    Object=[[PBRevealViewController alloc] init];
    
    PBRevealViewController *vc = [storyBoard instantiateViewControllerWithIdentifier:@"new"];

    [self.view addSubview:vc.view];
    but gesture are not working only show view and side bar is not showing check my code and correct

**Comment by iDevelopper** [comment]
Can you be more explicit, I don't understand what you want to do?

**Comment by alisattar456** [comment]
i want to move 1st view to 3rd view and then 3rd view back to 2nd view just as facebook only one time u give email address and password then when u close and and open again your account was open and directly go to dashboard i a making online app first you login and its save your login id after then when u close app and reopen again it checks tha login status if status=1 to goes to dashbaord without sign so so A,B,C are three view controller i want to A->C and then logout its go back to B and after then b->A

**Comment by iDevelopper** [comment]
This not a PBRevealViewController issue, but can you show a screenshot of your storyboard?
