### ISSUE TITLE
I want to disable interaction with front view when left or right views are revealed.Objective c

### ISSUE THREAD

**Issue by alisattar456** [iDevelopper/PBRevealViewController#18]

**Comment by iDevelopper** [comment]
Use the delegate methods:

```
- (void)revealController:(PBRevealViewController *)revealController willShowLeftViewController:(UIViewController *)controller
{
    revealController.mainViewController.view.userInteractionEnabled = NO;
}

- (void)revealController:(PBRevealViewController *)revealController willHideLeftViewController:(UIViewController *)controller
{
    revealController.mainViewController.view.userInteractionEnabled = YES;
}
```

**Comment by alisattar456** [comment]
where i  paste it in appdelegete in swrevealview controller or main view controller

**Comment by iDevelopper** [comment]
Where you want. You have to know what is a protocol and a delegate first! Your controller have to adopt the SWRevealViewController protocol and have to set the SWRevealViewController delegate to self for these methods be called. You could also subclass SWRevealViewController and set the delegate to this subclass.

**Comment by alisattar456** [comment]
I am uploading my sample project kindly implement the disable interaction with front view when left are revealed and in picture only open gesture is working for open menu but when click it close i want to close with gesture  in image 2 i am using webview in this view controller left is revealed successfull but no touch is wokring on webview or gesture to close reveal view

![screen shot 2016-11-14 at 2 14 39 pm](https://cloud.githubusercontent.com/assets/18255723/20285229/9064a062-aa75-11e6-8217-739923769cdd.png)
![screen shot 2016-11-14 at 2 29 09 pm](https://cloud.githubusercontent.com/assets/18255723/20285552/6e4bb73e-aa77-11e6-9109-e1cf32f35a0e.png)

[sampleproject.zip](https://github.com/iDevelopper/PBRevealViewController/files/590634/sampleproject.zip)

**Comment by iDevelopper** [comment]
1) I modified DashBordViewController.m for adopting PBRevealViewControllerDelegate protocol and add the two methods called when left is about to show or hide to set userInteractionEnabled to NO or YES on the main view.

2) PBRevealViewController do not provide a pan gesture for close left or right view. Only tap.

[Health-Appoinment1.zip](https://github.com/iDevelopper/PBRevealViewController/files/591209/Health-Appoinment1.zip)

**Comment by alisattar456** [comment]
what changes you have implemet can you define it i am add @interface DashBordViewController ()<PBRevealViewControllerDelegate> and - (void)revealController:(PBRevealViewController *)revealController willShowLeftViewController:(UIViewController *)controller {
    
    revealController.mainViewController.view.userInteractionEnabled = NO;
}

- (void)revealController:(PBRevealViewController *)revealController willHideLeftViewController:(UIViewController *)controller {
    revealController.mainViewController.view.userInteractionEnabled = YES;
}  
in my main project but interaction  demo project woking fine  1st i am adding protocol and then add these 2 functions in dashboard view controller what i other changes made to enable it

**Comment by alisattar456** [comment]
Thanks Very Much
