### ISSUE TITLE
RightView height and position.

### ISSUE THREAD

**Issue by Dbigshooter** [iDevelopper/PBRevealViewController#2]
Hi there, continuing from this thread. [https://github.com/John-Lluch/SWRevealViewController/issues/612](url)

Is it possible to get the RightView to stop by a tabBar? Minding that I just have the tabBar in the last controller, not in the navigationscontrollers before PBRevealViewController.

**Comment by iDevelopper** [comment]
Can you provide a screenshot please?

**Comment by Dbigshooter** [comment]
![sss](https://cloud.githubusercontent.com/assets/6803648/17937578/e628665c-6a22-11e6-9ea9-64198816765f.png)

**Comment by iDevelopper** [comment]
Do you have the application screenshot too? It is a tab bar? Not a tabbarcontroller?

**Comment by Dbigshooter** [comment]
![ssss](https://cloud.githubusercontent.com/assets/6803648/17938448/4733a148-6a26-11e6-9499-66d0ead26895.png)

**Comment by Dbigshooter** [comment]
Its is just a tabbar

**Comment by iDevelopper** [comment]
Hi @Dbigshooter , PBRevealViewController don't provide a way to do this yet! You can easily change the rightViewController's frame in your project.

See this sample, in SecondViewController.swift:

[Example6Swift.zip](https://github.com/iDevelopper/PBRevealViewController/files/436625/Example6Swift.zip)

**Comment by Dbigshooter** [comment]
@iDevelopper Can you reduce the height? Can I manually make it go to the tabBar just by declaring the height?

**Comment by Dbigshooter** [comment]
Can I get it to scroll under my navigation bar? When I scroll it looks like this:

<img width="165" alt="screen" src="https://cloud.githubusercontent.com/assets/6803648/17967479/b3db17b2-6ac7-11e6-8aa7-e5596fc32223.png">

**Comment by iDevelopper** [comment]
Did you try the last sample? It seems your constraints are not right. I added a text view to the right view controller and all is right:

[Example6Swift 2.zip](https://github.com/iDevelopper/PBRevealViewController/files/436911/Example6Swift.2.zip)

**Comment by Dbigshooter** [comment]
That is when I'm scrolling. Where did you set the constrains? I can see yours works perfectly.

**Comment by iDevelopper** [comment]
Yes but for me in my sample, it's ok. You can send your project if you want and I'll see.

**Comment by Dbigshooter** [comment]
Can you explain where you set the constraints? I'm using a TableViewController.

**Comment by iDevelopper** [comment]
![2016-08-25_14-45-30](https://cloud.githubusercontent.com/assets/1782450/17969541/d15f9cd0-6ad2-11e6-86d0-400c173e385d.png)

**Comment by Dbigshooter** [comment]
I see, but how can this be achieved in an TableViewController? I can't seem to do it.

**Comment by iDevelopper** [comment]
Ah ok, I thought it was a scrollView. Then embed your table view controller in a navigation controller, and in this navigation controller uncheck Show navigation bar.

[Example6Swift 3.zip](https://github.com/iDevelopper/PBRevealViewController/files/437052/Example6Swift.3.zip)

![2016-08-25_14-58-13](https://cloud.githubusercontent.com/assets/1782450/17969885/82eb081c-6ad4-11e6-86cb-76ae3a6aa209.png)

**Comment by iDevelopper** [comment]
And yes a table view controller and a particular object, it takes the whole screen. By adding a navigation controller in which  the bar is not shown, it takes into account the status bar's size. And sorry for my english!

**Comment by Dbigshooter** [comment]
You're a genius. Can I make the tableview not dragable? So the line stays where it is, see the last screenshot of mine.

**Comment by iDevelopper** [comment]
Not dragable? Meaning?

**Comment by Dbigshooter** [comment]
If I drag down, like if I want to update it, I don't want it to be dragged, I want it to be fixed.

![slice](https://cloud.githubusercontent.com/assets/6803648/17971213/23ea1c30-6ada-11e6-80c0-9b98b6de076d.png)

**Comment by iDevelopper** [comment]
Do you mean bounces property? Uncheck it.

![2016-08-25_15-44-53](https://cloud.githubusercontent.com/assets/1782450/17971480/52ef3154-6adb-11e6-8555-f3bff762521a.png)

**Comment by Dbigshooter** [comment]
Thanks! Is there a way to get the tabBar above the rightmenu? A hack or such?

**Comment by iDevelopper** [comment]
Try to add a shadow to your tabBar.

**Comment by Dbigshooter** [comment]
Oh I just realized, it's not a tabbar, but a toolbar! Is it possible to do it with that, @iDevelopper?

**Comment by iDevelopper** [comment]
I tried to add a 1px line (UIView with black background color) just above the tabBar in the story board. What about this?

![2016-08-25_17-38-12](https://cloud.githubusercontent.com/assets/1782450/17975733/19ac4f48-6aeb-11e6-81ee-a364a8973dfa.png)

**Comment by Dbigshooter** [comment]
It is a toolbar, not a tabbar, I figured. Does that make any difference?

**Comment by iDevelopper** [comment]
It is the same. They are both UIView.

**Comment by Dbigshooter** [comment]
Is that the only solution, or are you working on another?

**Comment by iDevelopper** [comment]
No, as it is not possible! The side view is shown on top of the main view then obviously above all the main view subviews.

**Comment by Dbigshooter** [comment]
But isn't the UIView you added a subview of the mainview? I just want to understand.

On the other hand, how to call a method on my mainView from the RightView?

**Comment by iDevelopper** [comment]
1) Yes it is.

2) revealViewController().mainViewController.yourMethod()
