### ISSUE TITLE
Feature Request!

### ISSUE THREAD

**Issue by Sebacho-Barajas** [iDevelopper/PBRevealViewController#20]
hi this is not an issue , this is a transition request
can you add one transition like this to the controller ? 
https://github.com/microeditionbiz/Custom-Transition

**Comment by Sebacho-Barajas** [comment]
is it possible to add this transition?

**Comment by iDevelopper** [comment]
This is not the purpose of PBRevealViewController who's manage a left and right side view controller. Why don't you use the one you have already?

https://github.com/microeditionbiz/Custom-Transition

**Comment by Sebacho-Barajas** [comment]
because that is a transition but not a menu controller, but thanks for your response!
