### ISSUE TITLE
Help me finding the way to implement it correctly

### ISSUE THREAD

**Issue by riyanpratamap** [iDevelopper/PBRevealViewController#21]
Hi, first of all this is great library! 
But I have one question regarding this implementation. So I created one project, and it has 3 menu item on its left menu controller. From each page on its menu, it has 3 button in bottom. See my picture 
<img width="677" alt="screen shot 2017-01-23 at 6 19 07 pm" src="https://cloud.githubusercontent.com/assets/4180343/22209606/b77f83d0-e1b9-11e6-97d0-c81e35c6f63a.png">

On `didSelectRowAtIndexPath`'s left menu table, I can "move" to 1,2, and 3 view controller by using
```
UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"MyStoryboard" bundle:nil];
UIViewController *controller = [[UINavigationController alloc] initWithRootViewController:[storyboard instantiateViewControllerWithIdentifier:@"MyStoryboardViewController"]];
[self.revealViewController pushMainViewController:controller animated:YES];
```

On 1, 2, and 3 View Controller, I initialize hamburger menu on navigation item with this
```
UIBarButtonItem *barButton = [[UIBarButtonItem alloc] init];
UIImage *imgBtn = [UIImage imageNamed:@"menu"];
[barButton setImage:imgBtn];

barButton.target = self.revealViewController;
barButton.action = @selector(revealLeftView);

self.revealViewController.toggleAnimationType = PBRevealToggleAnimationTypePushSideView;
self.navigationItem.leftBarButtonItem = barButton;
```

And each view controller has custom UIView that consist of 3 button. It is like bottom tab bar on Spotify for iOS. It will navigate to A, B, and C view controller that has slidemenu button also. 
<img width="629" alt="screen shot 2017-01-23 at 6 26 39 pm" src="https://cloud.githubusercontent.com/assets/4180343/22209723/1bbe2b44-e1ba-11e6-9d6b-92036117c920.png">

Right now, I can navigate to A, B, and C by creating delegate on its custom view that require instance of destination `UIViewController` as parameter so I can present that view controller using

`[self presentViewController:vc animated:YES completion:nil];`

But as the result, A, B, and C view controller can't initialize its slidemenu using code like on 1, 2, and 3 view controller. It hamburger menu is created, but it can't show slidemenu as it should be.

So where I did wrong here? I think my fault is on how to present A, B, and C view controller that use `presentViewController`. Or another one? Any sugestion would be appreciated. Thank you so much!

**Comment by iDevelopper** [comment]
Thanks a lot!

Are the A, B and C controllers the same when calling from left menu or from the bottom bar? Is the bottom bar a UITabBarController?

**Comment by iDevelopper** [comment]
Instead of:

```
[self presentViewController:vc animated:YES completion:nil];
```
Use:
```
[self.revealViewController setMainViewController:vc animated:YES];
```

In this case the vc controller presented will keep a revealViewController property as it is presented with it.

**Comment by riyanpratamap** [comment]
Wow, thank you sooo much! It works like a charm! Again, thank you so much!

**Comment by iDevelopper** [comment]
Welcome!
