### ISSUE TITLE
self.revealViewController set main viewcontroller programmatically

### ISSUE THREAD

**Issue by lorenzoPrimi** [iDevelopper/PBRevealViewController#25]
Hi all,
I need to change the view controller programmatically from one screen to another, so far I tried these solutions:

- NSNotification to the LeftViewController that tries a performSegueWithIdentifier
- Instantiate UINavigationController with FirstViewController in my SecondViewController and 
[self.revealViewController setMainViewController:navController]

- Same as above but in LeftViewController
- Same above but with pushMainViewController instead of setMainViewController
- Also tried to call [self.revealViewController revealLeftView] before any of these methods

**Comment by iDevelopper** [comment]
[self.revealController setMainViewController:animated:] does not work? (animated)

**Comment by lorenzoPrimi** [comment]
Thanks, with animated it works.
I was using animated: only on pushMainViewController
