### ISSUE TITLE
How to do push navigation on MainViewController from MenuViewController ?

### ISSUE THREAD

**Issue by tariq235** [iDevelopper/PBRevealViewController#27]
In MainViewController for any push action I can easily call 
`self.navigationController?.pushViewController(UIViewController(), animated: true)`

For changing mainViewController from menu then I can easily call 
`revealViewController().pushMainViewController(UIViewController(), animated:true)`

But for some cases, I would like MainViewController to perform pushViewController from Left menu screen. Is it really possible with this library ? Or I should check other library ? This is currently main requirement for my project design :(

**Comment by iDevelopper** [comment]
You can easily do that like this, from the left view controller:

```
            let controller = storyboard?.instantiateViewController(withIdentifier: "YourViewController")
            let navigationController = self.revealViewController().mainViewController as! UINavigationController
            navigationController.pushViewController(controller!, animated: true)
            self.revealViewController().hideLeftView(animated: true)
```
