### ISSUE TITLE
Works fine with UITableViewController but issue with UIViewController TableView

### ISSUE THREAD

**Issue by tariq235** [iDevelopper/PBRevealViewController#28]
![screen shot 2017-04-10 at 3 04 28 pm](https://cloud.githubusercontent.com/assets/349211/24849940/9be2ad7c-1e00-11e7-939d-ef6e6ceaaf97.png)

**Comment by iDevelopper** [comment]
Is this issue related to #27 one? If yes why create a new issue?

**Comment by tariq235** [comment]
Both are separate. I will verify and accept #27 
#28 Issue - When I left swipe then I see this weird UI.

**Comment by tariq235** [comment]
@iDevelopper I have attached edited sample code where you can use to reproduce the issue easily.
![screen shot 2017-04-10 at 5 27 14 pm](https://cloud.githubusercontent.com/assets/349211/24855128/2c27c0ea-1e13-11e7-9fbb-4898a1cfa831.png)
[PBRevealProgramExample_Test.zip](https://github.com/iDevelopper/PBRevealViewController/files/909594/PBRevealProgramExample_Test.zip)

**Comment by iDevelopper** [comment]
Because your table view have wrong constraints! Here is a sample for illustrate your three issues:

[PBRevealProgramExample.zip](https://github.com/iDevelopper/PBRevealViewController/files/909596/PBRevealProgramExample.zip)

**Comment by iDevelopper** [comment]
Thanks for helping!!! -:)
