### ISSUE TITLE
Swift version

### ISSUE THREAD

**Issue by iDevelopper** [iDevelopper/PBRevealViewController#31]
The Swift version of this library is now on line!
Please feel free to PR, Fork, etc...
And please tell me when you use this controller in your project !

**Comment by RFyre00** [comment]
I integrated side menu at left on a tabbarview controller and when swiping to close the menu  tabs also gets swiped. I am a rookie on this so please do help me out on how to disable swipe while menu is on top. Thank you.

**Comment by iDevelopper** [comment]
No sure to understand, can you upload your storyboard?

**Comment by RFyre00** [comment]
I mean both gesture recognizer of PBRevealController and SwipeableTabBarController are working at the same time. I want to disable the background user interaction while the side menu is open and  on the top.

**Comment by iDevelopper** [comment]
Ok,

Use the delegate functions:

```
    func revealController(_ revealController: PBRevealViewController, willShowLeft viewController: UIViewController)
    {
        revealController.mainViewController?.view.isUserInteractionEnabled = false
    }


    func revealController(_ revealController: PBRevealViewController, willHideLeft viewController: UIViewController)
    {
        revealController.mainViewController?.view.isUserInteractionEnabled = true
    }
```

**Comment by RFyre00** [comment]
thank you brother :)
