### ISSUE TITLE
Problem when using PBRVC in single side view context (i.e. a single left side menu)

### ISSUE THREAD

**Issue by pgmassari** [iDevelopper/PBRevealViewController#32]
I'm using the latest Pod spec (1.2.3) in a Swift project. In this project i need just one main VC and a single side VC as menu.

In the storyboard set up the PBRVC to have only `pb_main` and `pb_left` set.

So far, so good: the app behaves as expected.

The problem appears when i try to transition from an orientation to another (say, portrait to landscape or viceversa, depending on the initial orientation of the device/simulator). On transition, i get a runtime error due to this forced unwrap:
https://github.com/iDevelopper/PBRevealViewController/blob/20a755940ed36a21d41c2d841b509913d2341e28/PBRevealViewController/Classes/PBRevealViewController.swift#L2464
Possibly some other lines might cause unwrap problems too (although, I've been heavily using it with no other kinds of crash) 

To @iDevelopper: great work on this Swift reveal view controller. I tried many others (even with many more github stars) but this is simple, clear, efficient and _really_ working out of the box without having to hack around too much

**To those who need** to have PBRVC working in a single side menu context anyway (say, a left menu), I did the following: a) setup a dummy reference to `pb_right` and b) avoid the right side to appear when swiping from right to left, but only when the left side is not present (note: the right menu now show the same of the left side)
 
1.  in storyboard, set `pb_right` to the same VC as `pb_left` (so that the aforementioned unwrap wont be nil)
2.  subclass PBRVC and make it a `PBRevealViewControllerDelegate`
3.  stop this:
```
 func revealController(_ revealController: PBRevealViewController,
                        shouldShowRight viewController: UIViewController) -> Bool {
    return false
  }
```
4.  also, you'll need something to keep track that the left side is open (i use my MVC `alpha` value)
```
  func revealController(_ revealController: PBRevealViewController, willShowLeft viewController: UIViewController) {
    mainViewController?.view.isUserInteractionEnabled = false
    mainViewController?.view.alpha = 0.75
  }

  func revealController(_ revealController: PBRevealViewController, willHideLeft viewController: UIViewController) {
    mainViewController?.view.isUserInteractionEnabled = true
    mainViewController?.view.alpha = 1
  }
```
5. disable the swipe right to left to avoid the right side to come in (but keep it close the left side anyway)
```
func revealControllerPanGestureShouldBegin(_ revealController: PBRevealViewController,
                                             direction: PBRevealControllerPanDirection) -> Bool {
    if mainViewController?.view.alpha == 1,
      direction == .left {
      return false
    }

    mainViewController?.view.alpha = 1
    return true
  }
```

Probably there could be other faster & dirtier ways, like just setting `self.righViewRevealWidth = 0`

**Comment by iDevelopper** [comment]
Hi @pgmassari , thanks a lot for revealing this issue and for your great comment!

Fixed in 1.2.4

**Comment by pgmassari** [comment]
Thanks @iDevelopper for the fast fix.

Very good: confirmed working in 1.2.4, with just `pb_main` and `pb_left` set, while `pb_right` is not set.

No subclassing of PBRVC is necessary, unless customization is needed (i.e. `leftViewRevealWidth` or `leftViewBlurEffectStyle` in its `viewDidLoad`, ...)

**Comment by iDevelopper** [comment]
I like subclassing for the delegate functions but they should be in AppDelegate or elsewhere... Properties for customisation can be set in the main view controller also.

**Comment by pgmassari** [comment]
I'm fairly new to iOS development... is there a specific reason on why the delegate method should be in the AppDelegate class?

I liked the idea of having the "reveal vc stuff" in a respective subclass.

**Comment by iDevelopper** [comment]
No reason, but you said "No subclassing of PBRVC is necessary". I personally like subclassing my PBRevealViewController Class. All customisations and delegate implementations can be done in this subclass in rapport. (Note that you cannot subclass a Swift Class in Objective-C, for developers working in Objective-C and using Swift libairies).
