### ISSUE TITLE
SideMenu comes over the Viewcontroller over the tabBar and TopNavigationBar

### ISSUE THREAD

**Issue by jaisan123** [iDevelopper/PBRevealViewController#33]
@iDevelopper Can you please give sample code in swift 3 also with menu covering entire screen including top navigation bar and bottom tab bar?

i need the arrangement exactly like
https://github.com/John-Lluch/SWRevealViewController/files/275828/SWTabBarSwift2.zip
i want show viewcontrollers that are not in tapbar as a button (with tapbar in its footer,i mean whil e showing these vc's i want the bottom navigation bar in it also. ) as well as viewcontrollers in tabarcontroller also. 
but i need that side menu over the viewcontroller.please help @iDevelopper

**Comment by iDevelopper** [comment]
@jaisan123 , did you solve it? I was away.

**Comment by jaisan123** [comment]
@iDevelopper ,ya sir.you can mark as closed.Thanks for your response
