### ISSUE TITLE
Disable menu open and close by gestures?

### ISSUE THREAD

**Issue by gangelo** [iDevelopper/PBRevealViewController#39]
How do I prohibit the menu from opening and/or closing using gestures? I basically want to disable them because they are interfering with my UITableViewController cell swiping gestures.

**Comment by iDevelopper** [comment]
You can also implement the delegate function:

    /**
     Implement this to return NO when you want the pan gesture recognizer to be ignored.
     
     See also:
     
        panGestureRecognizer
     
     - Parameters:
        - revealController: The reveal view controller object.
        - direction:        The panning direction.

     - Returns:
        false if you want the pan gesture recognizer to be ignored, true otherwise.
     */
    @objc optional func revealControllerPanGestureShouldBegin(_ revealController: PBRevealViewController, direction: PBRevealControllerPanDirection) -> Bool

**Comment by graycampbell** [comment]
Hey @gangelo, you should be able to keep the opening and closing gestures while avoiding interference with UI elements on `mainViewController` using `PBRevealViewControllerDelegate`:

```
func revealController(_ revealController: PBRevealViewController, willShowLeft viewController: UIViewController) {

    revealController.mainViewController?.view.isUserInteractionEnabled = false
}
    
func revealController(_ revealController: PBRevealViewController, didHideLeft viewController: UIViewController) {

    revealController.mainViewController?.view.isUserInteractionEnabled = true
}

func revealController(_ revealController: PBRevealViewController, willShowRight viewController: UIViewController) {

    revealController.mainViewController?.view.isUserInteractionEnabled = false
}
    
func revealController(_ revealController: PBRevealViewController, didHideRight viewController: UIViewController) {

    revealController.mainViewController?.view.isUserInteractionEnabled = true
}
```
