### ISSUE TITLE
Black stripe while animation runs

### ISSUE THREAD

**Issue by schmidt9** [iDevelopper/PBRevealViewController#4]
See on screenshot (taken during animation) black line before main VC bounces back

![simulator screen shot 30 2016 9 35 12_](https://cloud.githubusercontent.com/assets/20910077/18079153/4116ebfc-6ea0-11e6-8d9a-c2becc861464.png)

**Comment by iDevelopper** [comment]
This is due to leftToggleSpringDampingRatio parameter. Set this property to 1.0. See Apple UIView reference:

animateWithDuration:delay:usingSpringWithDamping:initialSpringVelocity:options:animations:completion:

**Comment by schmidt9** [comment]
Thanks!
