### ISSUE TITLE
Switching to another view controller programtically

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [iDevelopper/PBRevealViewController#42]
Hi,

I have a setup like this.

![screen shot 2018-01-04 at 4 06 26 pm](https://user-images.githubusercontent.com/2551877/34560073-6f9c0892-f16a-11e7-8e62-e3a34f013252.png)

From the green view controller, I want to switch to the pink view controller when the user taps on the white button in the green view controller.

I tried the following code but nothing happens.

```swift
guard let revealViewController = revealViewController() else { return }
let twoViewController = storyboard!.instantiateViewController(withIdentifier: "TwoViewController") as! TwoViewController
let navController = UINavigationController(rootViewController: twoViewController)
revealViewController.pushMainViewController(navController, animated: true)
```

Is there a different way to do this?
 
Added a [demo project](https://www.dropbox.com/s/ery73czpvq6rk07/SideMenuDemo.zip?dl=0) here as well.

**Comment by iDevelopper** [comment]
Use (to replace the main view controller)

```
        revealViewController.setMainViewController(navController, animated: true)
```
instead of

```
        revealViewController.pushMainViewController(navController, animated: true)
```
[SideMenuDemo.zip](https://github.com/iDevelopper/PBRevealViewController/files/1603411/SideMenuDemo.zip)

**Comment by Isuru-Nanayakkara** [comment]
Thank you.
