### ISSUE TITLE
how to present a new viewController without hiding the bottom tab bar?

### ISSUE THREAD

**Issue by jaisan123** [iDevelopper/PBRevealViewController#44]
Im using pbreveal viewController to show side menu that comes over the bottom tab bar.Means,the side menu comes over the bottom bar and covers it. Now i want to present a new viewcontroller without hiding the bottom tab bar. 

I mean i have  2 tabs.tab 1 and 2.On clicking a button in tab 1, i need to present a new vc that comes just above the bottom tabbar and covers vertically as usually presentation is going on.  When im trying to do it,the new vc covers the entire screen.how can i begin the presention just above the tabbar .please help me

**Comment by iDevelopper** [comment]
Please have a look at Example3Swift witch present the side menu above the tab bar controller view:

[Simulator Screen Shot - iPhone 8 Plus - 2018-01-31 at 16.48.23.png.zip](https://github.com/iDevelopper/PBRevealViewController/files/1682297/Simulator.Screen.Shot.-.iPhone.8.Plus.-.2018-01-31.at.16.48.23.png.zip)

**Comment by MiGhorbani** [comment]
In that example you don't change the view, the changes happen in Main view

**Comment by iDevelopper** [comment]
Do you want to present this new view controller with PbRevealViewController or with a navigation controller or modally? Is this new view controller can reveal the side controller?
