### ISSUE TITLE
Problem with Right Menu.

### ISSUE THREAD

**Issue by FedericoSub** [iDevelopper/PBRevealViewController#45]
Hi I'm having trouble with code:

 if let indexPath = self.collectionView?.indexPathForItem(at: sender.location(in: self.collectionView)) {
            let num = indexPath.last
         
            if (imgBuddyArray[num!].nome) == "Aggiungi" {
                   print(imgBuddyArray[num!].nome)

                **let mainStoryboard:UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
                let desController = mainStoryboard.instantiateViewController(withIdentifier:     "BuddyTableViewController") as! BuddyTableViewController
                let newFrontViewController = UINavigationController.init(rootViewController:desController)
                revealViewController()?.pushMainViewController(newFrontViewController, animated: true)**

            }
            
        } else {
            
        }
This is for open BuddyTableViewController when I tapped un "Aggiungi" 
<img width="357" alt="schermata 2018-02-20 alle 10 10 40" src="https://user-images.githubusercontent.com/35109594/36415544-9a668468-1626-11e8-9c39-0ac5a00345a7.png">

This is BuddyTableViewController:
<img width="352" alt="schermata 2018-02-20 alle 10 12 05" src="https://user-images.githubusercontent.com/35109594/36415611-d34a4760-1626-11e8-80cc-5d569f0c1d21.png">

This VC is opened correctly from the right menu when I tapped on "Amici" using the same code above, but the first VC doesn'work

<img width="350" alt="schermata 2018-02-20 alle 10 11 46" src="https://user-images.githubusercontent.com/35109594/36415703-19a4c4c4-1627-11e8-9549-d3ed5b0f3add.png">
any suggest ?

thanks

**Comment by iDevelopper** [comment]
Do you mean that when you tap on Home nothing happens?

**Comment by FedericoSub** [comment]
No ,  when I tapped on button "Aggiungi" (on bottom side)
![tap](https://user-images.githubusercontent.com/35109594/36475046-67c2a110-16f1-11e8-8bdf-cb68fcb2c802.gif)


 I'd like to open the BuddyTableViewController.
https://user-images.githubusercontent.com/35109594/36415611-d34a4760-1626-11e8-80cc-5d569f0c1d21.png

On tap of button I used the same code that works un menu (tap on Amici) but nothing happens.

![amici](https://user-images.githubusercontent.com/35109594/36475233-ee0e1b82-16f1-11e8-80ca-0c2e430b6a94.gif)

**Comment by FedericoSub** [comment]
If you need I can attach all code..

**Comment by iDevelopper** [comment]
Yes if you can, because it is very difficult to help without it.

**Comment by FedericoSub** [comment]
can I drag some file in .zip here?

**Comment by FedericoSub** [comment]
in ProfiloROTableViewController  you can find this func that if you Tapped  on  circle image   I'd like open BuddyTableViewController

 @objc func tap(sender: UITapGestureRecognizer){
           
        if let indexPath = self.collectionView?.indexPathForItem(at: sender.location(in: self.collectionView)) {
            let num = indexPath.last
         
            if (imgBuddyArray[num!].nome) == "Aggiungi" {
                   print(imgBuddyArray[num!].nome)
                let mainStoryboard:UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
                let desController = mainStoryboard.instantiateViewController(withIdentifier: "BuddyTableViewController") as! BuddyTableViewController
                let newFrontViewController = UINavigationController.init(rootViewController:desController)
                revealViewController()?.pushMainViewController(newFrontViewController, animated: true)
            }
            
        } else {
            
        }
        
        
        
    }












[Archivio 2.zip](https://github.com/iDevelopper/PBRevealViewController/files/1747626/Archivio.2.zip)

**Comment by iDevelopper** [comment]
Could you attach the project, not only the swift files? Archive the folder that contains the xcodeproj file.

**Comment by FedericoSub** [comment]
can I send with wetransfer  ?  is too big .

can I have your email?

**Comment by iDevelopper** [comment]
patrick.bodet4@wanadoo.fr

**Comment by FedericoSub** [comment]
sent with wetransfer 
thanx

**Comment by iDevelopper** [comment]
Ok, pushMainViewController is for pushing a new controller from left or right side view controller. In this case you want to replace the main view controller. Use setMainViewController instead of pushMainViewController:

```
    @objc func tap(sender: UITapGestureRecognizer){
        if let indexPath = self.collectionView?.indexPathForItem(at: sender.location(in: self.collectionView)) {
            let num = indexPath.last
         
            if (imgBuddyArray[num!].nome) == "Aggiungi" {
                   print(imgBuddyArray[num!].nome)
                let mainStoryboard:UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
                let desController = mainStoryboard.instantiateViewController(withIdentifier: "BuddyTableViewController") as! BuddyTableViewController
                let newFrontViewController = UINavigationController.init(rootViewController:desController)
//                revealViewController()?.pushMainViewController(newFrontViewController, animated: true)
                revealViewController()?.setMainViewController(newFrontViewController, animated: true)
            }
            
        } else {
            
        }
    }
```

**Comment by FedericoSub** [comment]
thanks Patrik works fine now .....sorry for my stupid question :-)  I'm a beginner with swift
Thanks again

**Comment by iDevelopper** [comment]
Ok, there is no stupid question! Most important is that it works :-)

**Comment by FedericoSub** [comment]
Just last help....how can I close the menu when is open with gesture ?
thanks

**Comment by iDevelopper** [comment]
In MainTableViewController.swift, remove:

```
        self.revealViewController()?.panFromLeftBorderWidth = 50
```
```
    override func viewDidLoad() {
        super.viewDidLoad()

        // Keep a reference to this controller
        let rightController = self.revealViewController()?.rightViewController as! UINavigationController
        let rightTableViewController = rightController.topViewController as! MenuViewController
        rightTableViewController.navMainController = self.navigationController
        //
        
        rightButton.target = self.revealViewController()
        rightButton.action = #selector(PBRevealViewController.revealRightView)
        
        self.revealViewController()?.isRightPresentViewOnTop = false
        self.revealViewController()?.rightViewRevealWidth = 210
        
        self.revealViewController()?.delegate = self
        
        //self.revealViewController()?.panFromLeftBorderWidth = 50
        self.revealViewController()?.panFromRightBorderWidth = 50
   
        updateView()
        
        //MARK make navbar trasparent
        let bar:UINavigationBar! =  self.navigationController?.navigationBar
        bar.setBackgroundImage(UIImage(), for: UIBarMetrics.default)
        bar.shadowImage = UIImage()
    }
```

**Comment by iDevelopper** [comment]
Other things: Don't forget to always call the superview methods:

        super.viewDidDisappear(animated)
        super.viewWillAppear(animated)

For example:

```
    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)

        ref.removeObserver(withHandle: handle)
    }
 
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        if let user = Auth.auth().currentUser {
            
            useridIniziale = user
            let newUser = Database.database().reference().child("users").child((useridIniziale?.uid)!)
            newUser.updateChildValues(["Token": Messaging.messaging().fcmToken ?? ""])
            
            news.removeAll()
 
            leggiDati()
            
            tableView.reloadData()
        }
    }
```

**Comment by FedericoSub** [comment]
:-)
thanks
