### ISSUE TITLE
Nothing happens when clicked on side menu button

### ISSUE THREAD

**Issue by umairqureshi6** [iDevelopper/PBRevealViewController#46]
i have implemented side menu using Objective C version
nothing happens when i click on side menu button

i have implemented using example from github

**Comment by iDevelopper** [comment]
Can you elaborate please? Do you use Storyboard? Is you side menu button well connected to IBOutlet? Can you provide some lines of code?

**Comment by umairqureshi6** [comment]
yes i am using a storyboard, side menu button is well connected to IBOutlet have placed this code in UIViewController class

`- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator
{
    [coordinator animateAlongsideTransition:^(id<UIViewControllerTransitionCoordinatorContext> context)
     {
     }
                                 completion:^(id<UIViewControllerTransitionCoordinatorContext> context)
     {
         
     }];
    
    [super viewWillTransitionToSize:size withTransitionCoordinator:coordinator];
}`

using this code in viewdidload

`    _leftButton.target = self.revealViewController;
    _leftButton.action = @selector(revealLeftView);
    
    _rightButton.target = self.revealViewController;
    _rightButton.action = @selector(revealRightView);
    
//    self.revealViewController.leftPresentViewHierarchically = YES;
//    self.revealViewController.rightPresentViewHierarchically = YES;
    
    //self.revealViewController.leftToggleAnimationDuration = 0.8;
    self.revealViewController.toggleAnimationType = PBRevealToggleAnimationTypeSpring;`

**Comment by iDevelopper** [comment]
I don't see anything wrong here. Can you provide a project example?

**Comment by iDevelopper** [comment]
Is the class of your MainViewController is set in the storyboard?

**Comment by umairqureshi6** [comment]
(https://www.dropbox.com/s/w8nblbycbl3u88k/Daleelo.zip?dl=0)

**Comment by iDevelopper** [comment]
This link is broken (404).

However, here is a startup sample:

[PBRevealSampleObjc.zip](https://github.com/iDevelopper/PBRevealViewController/files/1806906/PBRevealSampleObjc.zip)

**Comment by umairqureshi6** [comment]
you can check that link now!

**Comment by iDevelopper** [comment]
The segue from PBRevealViewController to MenuTableViewController (identifier: pb_left) in your storyboard must be a subclass of PBRevealViewControllerSegueSetController (not PBRevealViewControllerSeguePushController).
