### ISSUE TITLE
Changing viewController removes my navigationbar settings

### ISSUE THREAD

**Issue by hopstad** [iDevelopper/PBRevealViewController#48]
Hello.

Im changing my ViewController doing this : 

```
let nc = UINavigationController(rootViewController: controller!)
revealViewController()?.setMainViewController(nc, animated: true)
```
![test](https://user-images.githubusercontent.com/1426101/39620734-61f49850-4f8c-11e8-9ead-45de9e517518.jpg)

Its working fine but my NavigationControllers (Name App Navigation Controller in picture) settings seems to get reset. At first launch the colors are correct. After swapping the ViewController with the code above everything is reset to standard. What happens to the NavigationController during changing ViewController? Im also no longer able to reach it from the ViewController after a swap

So : At first launch. "Dashboard Tab Controller"s NavigationBar looks correct and it can talk to "App Nav Controller".
After changing the ViewController NavigationBar is reset and I can no longer reach the "App Nav Controller"

**Comment by iDevelopper** [comment]
Where does this controller come from?

**Comment by hopstad** [comment]
> Where does this controller come from?

You mean the ViewController I want to change to? Its just floating on the storyboard. Loaded like this: 

`controller = storyboard.instantiateViewController(withIdentifier: "Dashboard")`

**Comment by iDevelopper** [comment]
So it is logic, you instantiate a new instance of your controller then it is re-initialized (viewDidLoad etc...). Either you save your settings somewhere (NSUserDefault for example) or you keep a reference of this controller to avoid instantiate it again and for reuse.

**Comment by hopstad** [comment]
Thanks for reply. Maybe I misunderstand or my question is unclear. What I would want to achieve is to always keep the NavigationController (App Nav Controller in screenshot). It will be the head of the umbrella in my app. So what I would want is for this to allways be there but only change the root view controller of it.

**Comment by iDevelopper** [comment]
Ok then do not allocate a new one. Retrieve it like this:

        let nc = self.revealViewController().mainViewController as? UINavigationController

**Comment by hopstad** [comment]
Solved by using your example combined with some other code changing. Thanks for your help @iDevelopper ! Have a good weekend

**Comment by iDevelopper** [comment]
Thanks, you too :-)
