### ISSUE TITLE
Ability to slide the main window 

### ISSUE THREAD

**Issue by justdan0227** [iDevelopper/PBRevealViewController#53]
Does this have the ability to slide the main view controller along with the fly out menu or is it only overlay?

**Comment by iDevelopper** [comment]
Like SW?

**Comment by justdan0227** [comment]
Yes sorry like SW.  I need the hamburger menu to slide over with the menu and slide the current view controller

**Comment by iDevelopper** [comment]
Use:
```
        self.revealViewController()?.isLeftPresentViewOnTop = false
```

The same property exists also for right view (isRightPresentViewOnTop)

[PBRevealDeinit.zip](https://github.com/iDevelopper/PBRevealViewController/files/2361332/PBRevealDeinit.zip)

**Comment by justdan0227** [comment]
WOW.. ok this library rocks!   Yep that worked perfectly!  Thanks!

**Comment by iDevelopper** [comment]
Welcome! You can test the sample project named "ExampleWithSwiftLibrary" in the repo for severals parameters. Open the left menu and select Settings:

<img width="426" alt="capture d ecran 2018-09-08 a 18 48 07" src="https://user-images.githubusercontent.com/1782450/45256559-43e0b180-b398-11e8-9132-422960d4488d.png">
