### ISSUE TITLE
Migrate to Swift 4.2

### ISSUE THREAD

**Issue by pgmassari** [iDevelopper/PBRevealViewController#54]
Hi there @iDevelopper 

are you planning to update PBRVC to Swift 4.2?

**Comment by iDevelopper** [comment]
Yes I will. Try to do this during this week-end.

**Comment by iDevelopper** [comment]
Hi @pgmassari ,

You can use the Swift 4.2 version of PBRevealViewController:

Github:
https://github.com/iDevelopper/PBRevealViewController/tree/swift-4.2 (swift-4.2 branch).

CocoaPods (in your podfile):
pod 'PBRevealViewController/Swift', :git => 'https://github.com/iDevelopper/PBRevealViewController.git', :branch => 'swift-4.2'

Feedback is welcome!
