### ISSUE TITLE
Sliding panel similar to SWReveal

### ISSUE THREAD

**Issue by prakashmaharjan** [iDevelopper/PBRevealViewController#57]
Is there a way to achieve the animation of revealing like SWRevealController. 
i.e to slide the main controller with top navigation button moving along instead of left view covering and sliding over top of main view and nagivattion button?

Something similar to this?

![sidebar-9](https://user-images.githubusercontent.com/8100150/50068055-2075a000-01ec-11e9-983e-62d98488c13c.png)

Thank you for the great and upto date library.

**Comment by iDevelopper** [comment]
Thanks for you last comment.

To push like SW, set this property to false, default is true:
```
    /**
     If false (default is true) the left view controller will be presented below the main view controller.
     */
    open var isLeftPresentViewOnTop: Bool = true
```
There is the same property for the right side view controller:
```
    /**
     If false (default is true) the right view controller will be presented below the main view controller.
     */
    open var isRightPresentViewOnTop: Bool = true
```

**Comment by PrakashMaharjan** [comment]
Thank you for the help. It worked.
However, I am trying to disable user interaction in the front view when revel menu view is opened.
But it's not working. Any help?

I have used this code in left menu view to do so, but it does not prevent from the user interaction on front view when revel view is opened. I used same code in SWRevealController it worked but in it is not working in PBReveal.

override func viewWillAppear(_ animated: Bool) {
super.viewWillAppear(animated)

self.revealViewController()?.delegate = self; self.revealViewController()?.mainViewController?.view.isUserInteractionEnabled = false
self.revealViewController()?.view.addGestureRecognizer((self.revealViewController()?.panGestureRecognizer)!)    
   
}
    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)

        self.revealViewController()?.mainViewController?.view.isUserInteractionEnabled = true
    }
    override func viewDidLoad() {
        super.viewDidLoad()

        self.revealViewController()?.panGestureRecognizer
        self.revealViewController()?.tapGestureRecognizer
}


Thank you.

**Comment by prakashmaharjan** [comment]
Thank you for the help. It worked.
However, I am trying to disable user interaction in the front view when revel menu view is opened.
But it's not working. Any help?

I have used this code in left menu view to do so, but it does not prevent from the user interaction on front view when revel view is opened. I used same code in SWRevealController it worked but in it is not working in PBReveal.

override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    
    self.revealViewController()?.delegate = self
    self.revealViewController()?.mainViewController?.view.isUserInteractionEnabled = false
    self.revealViewController()?.view.addGestureRecognizer((self.revealViewController()?.panGestureRecognizer)!)
    
}
override func viewDidDisappear(_ animated: Bool) {
    super.viewDidDisappear(animated)
    
    self.revealViewController()?.mainViewController?.view.isUserInteractionEnabled = true
}
override func viewDidLoad() {
    super.viewDidLoad()
    
    self.revealViewController()?.panGestureRecognizer
    self.revealViewController()?.tapGestureRecognizer
}


Thank you.

**Comment by iDevelopper** [comment]
Adopt the PBRevealViewControllerDelegate protocol and implement the delegate method, in your left view controller or in a PBRevealViewController subclass (better):

```
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.revealViewController()?.delegate = self
        
        // ...
    }
```

```
extension TableViewController: PBRevealViewControllerDelegate {
    func revealController(_ revealController: PBRevealViewController, willShowLeft viewController: UIViewController) {
        revealController.mainViewController?.view.isUserInteractionEnabled = false
    }
    
    func revealController(_ revealController: PBRevealViewController, willHideLeft viewController: UIViewController) {
        revealController.mainViewController?.view.isUserInteractionEnabled = true
    }
}
```
Also you do not need to call panGestureRecognizer and tapGestureRecognizer, the library does it for you automatically.

**Comment by PrakashMaharjan** [comment]
where do i put this extension code in left reveal view?

**Comment by prakashmaharjan** [comment]
where do i put this extension code? In left reveal view?

**Comment by iDevelopper** [comment]
In left view controller, yes, as the sample shown. TableViewController is the left reveal view controller. Else, you can also subclass PBRevealViewController to manage your delegate methods in it.

**Comment by prakashmaharjan** [comment]
Thank you for the help, but not sure why its not working for me, or what I am missing.
Is there anything more needed to do?

I have attached the project sample code so that you can guide me.

[PBRevealDemo.zip](https://github.com/iDevelopper/PBRevealViewController/files/2691283/PBRevealDemo.zip)


Thank you.

**Comment by iDevelopper** [comment]
In your project demo you set the delegate twice: In HomeViewController (function setUpReveal) and in LeftPanelViewController. The delegate is HomeViewController because his viewDidLoad is called after the viewDidLoad of LeftPanelViewController. So, WillShowLeft and WillHideLeft are not fired on LeftPanelViewController. You have to set only one delegate.

**Comment by prakashmaharjan** [comment]
So if i set only one delegate in left view then will the delegate in main (front)view work?
When i do so, then delegate function in main view does not seem to fire and swiping of the reveal is not working from edge. Reveal is opened even from the middle of the screen on swiping. How to take care of this? Also the page menu swipe is conflicting with reveal swipe. 

// MARK: - PBREVEAL CONTROLLER DELEGATE
    func revealControllerPanGestureShouldBegin(_ revealController: PBRevealViewController, direction: PBRevealControllerPanDirection) -> Bool {
        
        let point = revealController.panGestureRecognizer!.location(in: view)
        if !revealController.isLeftViewOpen && direction == .right && point.x < 50.0 {
            return true
        }
        if !revealController.isRightViewOpen && direction == .left && point.x > (view.bounds.size.width - 50) {
            return true
        }
        if revealController.isLeftViewOpen || revealController.isRightViewOpen {
            return true
        }
        return false
        
        
        
    }
    
    func revealController(_ revealController: PBRevealViewController, tapGestureRecognizerShouldRecognizeSimultaneouslyWithGestureRecognizer otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        return true
    }

**Comment by iDevelopper** [comment]
No, you must have only one delegate. You can implement all the delegate functions in LeftPanelViewController. And for pan from edge, there are some properties (since version 1.2.2) named panFromLeftBorderWidth and panFromRightBorderWidth.

You can otherwise subclass PBRevealViewController for your delegate. I will send a sample.

**Comment by iDevelopper** [comment]
[PBRevelIssue57.zip](https://github.com/iDevelopper/PBRevealViewController/files/2692095/PBRevelIssue57.zip)

**Comment by prakashmaharjan** [comment]
Thank you very much for the effort you made into this.

Is it good to set the constant hardcoded for pan border?

self.panFromLeftBorderWidth = 50
self.panFromRightBorderWidth = 50

While that is set to 50 value, I got behavior that I can drag the reveal view from left edge around to 50 width and open the reveal, but while closing down the reveal, i.e swiping from right to left it does not close the reveal from left edge of front view ie border line. It only closes or drag back when dragging is done some 50 width to right from the edge line. 

Also the alpha value shows flickering effect and when dragged slowly. like this:

![simulator screen shot - iphone 7 plus - 2018-12-19 at 15 01 33](https://user-images.githubusercontent.com/8100150/50211736-6f186b00-03a1-11e9-8cf8-38c3513dd862.png)


However, when i comment these lines of hardcode border

self.panFromLeftBorderWidth = 50
self.panFromRightBorderWidth = 50

and uncomment this delegate, then it works fine. What is your suggestion on this?
Thank you.

func revealControllerPanGestureShouldBegin(_ revealController: PBRevealViewController, direction: PBRevealControllerPanDirection) -> Bool {
        
        let point = revealController.panGestureRecognizer!.location(in: view)
        if !revealController.isLeftViewOpen && direction == .right && point.x < 50.0 {
            return true
        }
        if !revealController.isRightViewOpen && direction == .left && point.x > (view.bounds.size.width - 50) {
            return true
        }
        if revealController.isLeftViewOpen || revealController.isRightViewOpen {
            return true
        }
        return false
    }

**Comment by iDevelopper** [comment]
This is because you don't have a right view controller. Try to comment:
```
        // self.panFromRightBorderWidth = 50
```
But needs more investigation to see the behaviour in case where there are left and right view controllers and to see if some fix are needed.

**Comment by prakashmaharjan** [comment]
Yes, I agree that's works when done so.

One last question, how can i handle the swipe of reveal while there is component like Pagemenu in the front view. The swiping of the reveal is blocked by page menu swipe. I want to detect the swiping of reveal as it is from the edge, but the swiping or scrolling of page menu prevents the reveal to swipe. 

I have thought to add the page menu in front view with some margin at left so that the reveal can be swiped from left edge.
Is there any better way or sugestion to solve this?

Thank you.

**Comment by iDevelopper** [comment]
I am having a look to PageMenu that I don't know. First, why do you not use the whole framework but just CAPSPageMenu.swift? and in the demo project you sent to me yesterday the menu of page menu is not shown...

**Comment by iDevelopper** [comment]
To allow the reveal pan gesture with PageMenu, implement the delegate method (be careful, there are two methods, one for tap and one for pan): 

```
    func revealController(_ revealController: PBRevealViewController, panGestureRecognizerShouldRecognizeSimultaneouslyWithGestureRecognizer otherGestureRecognizer: UIGestureRecognizer, direction: PBRevealControllerPanDirection) -> Bool {
        return true
    }
```

**Comment by prakashmaharjan** [comment]
Thank you so much for the help.
You can now close this issue.

Thank you once again.

**Comment by iDevelopper** [comment]
I have fixed a little bug for some case in PBRevealViewController.

You can either install the swift version 4.2 (branch Swift-4.2) or version 4.

I wrote a sample, in witch I have installed PageMenu via Cocoapods, with some workaround because the PageMenu gesture recognizers delegate  and scrollviews delegate are not forwarded to the app. Hopes it is a begin point to help.

[PBRevealWithPageMenu.zip](https://github.com/iDevelopper/PBRevealViewController/files/2700091/PBRevealWithPageMenu.zip)

**Comment by prakashmaharjan** [comment]
Thank you for the great effort and great library.
I will be using the latest version.

Thank you.

**Comment by iDevelopper** [comment]
Welcome, closing this issue.
