### ISSUE TITLE
How to use it without storyboard?

### ISSUE THREAD

**Issue by davamp** [iDevelopper/PBRevealViewController#59]

**Comment by iDevelopper** [comment]
With the init function:
```
    /**
     Instantiate a PBRevealViewController class programmatically
     
     - Parameters:
        - leftViewController:  A subclass of UIViewController (optional).
        - mainViewController:  A subclass of UIViewController (required).
        - rightViewController: A subclass of UIViewController (optional).

     - Returns:
        PBRevealViewController instance.
     */
    @objc public init(leftViewController: UIViewController?, mainViewController: UIViewController, rightViewController: UIViewController?)
```
Example:
[PBRevealIssue59.zip](https://github.com/iDevelopper/PBRevealViewController/files/2718260/PBRevealIssue59.zip)

**Comment by davamp** [comment]
Thank for answer my question.That's a great help

**Comment by sfilo** [comment]
For others interested, there is an example in the PBRevealViewController Example Project but I found you have to define Storyboard ID for the three views and also add main window initialisation and configuration to get it to work.

`self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    self.window.rootViewController = revealController;`
`[self.window makeKeyAndVisible];`
