### ISSUE TITLE
How can I prevent interaction with main view

### ISSUE THREAD

**Issue by jumper4000** [iDevelopper/PBRevealViewController#61]
Hi, I'm trying to do this - https://github.com/iDevelopper/PBRevealViewController/issues/3 in Swift, but I'm not sure how to use a delegate method - 

Would you be able to tell me how to set that up in Swift?

Thanks for all the work and the help.

**Comment by iDevelopper** [comment]
Your delegate controller must adopt PBRevealViewControllerDelegate. Any view controller can be the delegate, but I think the better is to subclass PBRevealViewController. In this view controller, implement the delegate methods as in this example:

[PBRevealIssue61.zip](https://github.com/iDevelopper/PBRevealViewController/files/2730506/PBRevealIssue61.zip)

**Comment by jumper4000** [comment]
Thank you. That worked. I'm kinda new to iOS development, so that example was very helpful. I appreciate it very much :)
