### ISSUE TITLE
Facebook banner ad or google admob in all view (Question, Help needed)

### ISSUE THREAD

**Issue by prakashmaharjan** [iDevelopper/PBRevealViewController#62]
Hi,

What would be best approach to add facebook banner ad or google admob in all view with reveal controller. i.e in all views. Do we have to write adding banner to all views? or any other better approach from appdelegate etc?
Any suggestion or recommendation?

**Comment by iDevelopper** [comment]
There is no best approach. PBRevealViewController is a container view controller and it does not display anything. You have to insert the banner in each view controller you want. I think your AppDelegate should be the delegate object for request and receive Ad to send notification when received. However, the best way is to ask the question on SO.

**Comment by prakashmaharjan** [comment]
Is there way that we can add the banner always to be displayed on pushed front view controller?
I have added ad in one front view controller as subview.
But when I switch to next view from left menu i.e set another view as front view controller, then the banner view is hidden. How to get the current front view so that i can show banner it to the added front view.

As there are lots of views that i push or set from left menu table tap, I feel there will be lots of boiler plate delegates code to add in all views. 


Thanks

**Comment by iDevelopper** [comment]
You should have a base subclass for all your view controllers.
