### ISSUE TITLE
Black screen when starting

### ISSUE THREAD

**Issue by ccannell** [iDevelopper/PBRevealViewController#63]
I'm having an issue getting setup. I'm using Swift 4.2, programmatically creating UI, and separating the UIViewController and UIView into separate files. I started from the example you provided in a zip on issue [#59](https://github.com/iDevelopper/PBRevealViewController/issues/59). The example works fine as written, however, if I change _MainViewController.swift_ to the following:

```
import UIKit

class MainViewController: UIViewController {
    
    override func loadView() {
        view = MainView()
    }
}
```

and create _MainView.swift_ with the following:

```
import UIKit

class MainView: UIView {

    override init(frame: CGRect) {
        super.init(frame: frame)
        setupView()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setupView()
    }
    
    func setupView() {
        self.backgroundColor = .white
    }
}
```

I do not see a white background. I get a black background. I have separated the _UIView_ and _UIViewController_ in other projects successfully but it doesn't appear to play with with _PBRevealViewController_. Any help would be appreciated. Thanks.

**Comment by iDevelopper** [comment]
It seems that your view has a frame equal to zero.

Try
```
        view = MainView(frame: UIScreen.main.bounds)
```

**Comment by ccannell** [comment]
That did it. Thank you very much!
