### ISSUE TITLE
SWRevealViewController to PBRevealViewController "FrontViewPosition"

### ISSUE THREAD

**Issue by ghost** [iDevelopper/PBRevealViewController#67]
Salut Patrick,
Je suis en train de remplacer SWRevealViewController par PBRevealViewController et je n'arrive pas a comprendre comment remplacer :
- (void)revealController:(PBRevealViewController *)revealController didMoveToPosition:(FrontViewPosition)position { if ( position == FrontViewPositionRight ) { 
Si tu veux bien me mettre sur la voie.
Merci

**Comment by iDevelopper** [comment]
Hello,

Cette méthode n'existe pas dans le framework PBRevealViewController.

Il faut utiliser:

```
/**
 *  Called just after the left view controller is presented.
 *
 *  @param revealController The reveal view controller object.
 *  @param controller       The left view controller object.
 */
- (void)revealController:(PBRevealViewController *)revealController didShowLeftViewController:(UIViewController *)controller;
```
Et donc il n'y a pas lieu de tester la position.

**Comment by ghost** [comment]
Merci, j'apprecie. Il y aura probablement d'autres questions PBRevealViewcontroller.
