### ISSUE TITLE
Do you have plans to update to Swift 5?

### ISSUE THREAD

**Issue by Quailcreek** [iDevelopper/PBRevealViewController#70]
Hi,
every time I update the pods on my project I get about 50 errors in PBRevealViewController. Do you plane to do an updated to Swift 5?

Thanks,
Tom

**Comment by iDevelopper** [comment]
Hi,
You should not. Did you change the swift version in the pod building settings?
Do you use the swift-4.2 branch?

**Comment by Quailcreek** [comment]
Sorry! I should have realized the errors were from swift 4.2. That fixed it.

Thanks

**Comment by iDevelopper** [comment]
Great!
