### ISSUE TITLE
Swipe to delete UITableView

### ISSUE THREAD

**Issue by justdan0227** [iDevelopper/PBRevealViewController#77]
Trying to get swipe to delete a row on table view.  Do I need to disable pan left while on this view?

**Comment by iDevelopper** [comment]
Where is this table view (On left, main or right view controller)?

Is it a table view controller? Or a table view in a view controller?

Do you have a right view controller?

**Comment by justdan0227** [comment]
So sorry did not see this reply.. so my table view is in the main view and I want to allow swipe to delete without affecting the left view controller (right is not used)

**Comment by iDevelopper** [comment]
You can use:
```swift
    override func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath) -> [UITableViewRowAction]?
```
Or:
```swift
    override func tableView(_ tableView: UITableView, canEditRowAt indexPath: IndexPath) -> Bool
```
and
```swift
    override func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle, forRowAt indexPath: IndexPath)
```

**Comment by marcotuliofr** [comment]
I had the same issue. The delegate swipe methods of table view aren't been called. I tried with UITableViewController, and UITableView within UIViewController.
What resolve to me: 
In the view that i need the tableView delegate work. (inside viewdidAppear)
`self.revealViewController()?.panGestureRecognizer?.isEnabled = false`

The others view that use RevealController (in my case the mainView is a TabBar, in the viewDidAppear method too)
`self.revealViewController()?.panGestureRecognizer?.isEnabled = true`

Hope it help u.
