### ISSUE TITLE
Dismiss left view

### ISSUE THREAD

**Issue by justdan0227** [iDevelopper/PBRevealViewController#78]
Sorry.. I'm not seeing what I call in my menuViewController (left) to dismiss the menu (when you select a menu option that does not do any replacing or segeues, just want it to dismiss the menu animated).

**Comment by iDevelopper** [comment]
```swift
revealViewController.revealLeftView()
```
will close the left menu if it is open.

Or:
```swift
revealViewController.hideLeftView(animated: true)
```

**Comment by justdan0227** [comment]
Thanks!  I knew it would be simple!
