### ISSUE TITLE
Issue with customization leftView 

### ISSUE THREAD

**Issue by Sebacho-Barajas** [iDevelopper/PBRevealViewController#8]
I know this Class is not the same as swrevealviewcontroller but it is very similar , I'm transitioning from SWRevealviewcontroller, in my leftview i used to have a tableview customized with a gradient but when I started to use PBrevealviewcontroller the tableview background appears with white color and I also have an issue with the statusbar as I need it to show uistatusbarlightcontent(with SWRevealviewcontroller it used the statusbar from the viewcontroller) .

**Comment by iDevelopper** [comment]
Regarding your table view, could you test with the last version please (on Github), not yet on CocoaPods. PBRevealViewController class does nothing with the status bar appearance. Waiting for your feedback.

**Comment by Sebacho-Barajas** [comment]
Hi i used the latest update and i'm still getting same issue with tableview, all my customizations are done programmatically(Objective C) .
I fixed statusbar by adding  - (UIStatusBarStyle)preferredStatusBarStyle {
    return UIStatusBarStyleLightContent;
}

**Comment by Sebacho-Barajas** [comment]
Update: I can customize de tableview background Color and cells height programmatically.
but it does not work with [self.tableView setBackgroundView = myview]; as it supposed to do

**Comment by iDevelopper** [comment]
Any apologies, it's my fault. I corrected and pushed on Github and this is a sample:

[PBRevealSample.zip](https://github.com/iDevelopper/PBRevealViewController/files/504799/PBRevealSample.zip)

For the status bar:

![2016-10-02_07-41-48](https://cloud.githubusercontent.com/assets/1782450/19018955/65a59c14-8874-11e6-9004-4580ee12c829.png)
![2016-10-02_07-38-00](https://cloud.githubusercontent.com/assets/1782450/19018956/65d7009c-8874-11e6-9882-13fe5976d254.png)

**Comment by Sebacho-Barajas** [comment]
thanks it's working properly now!
