### ISSUE TITLE
Warning: Attempt to present <UINavigationController: 0x7c284400> on <PBRevealViewController

### ISSUE THREAD

**Issue by turganbekuly** [iDevelopper/PBRevealViewController#80]
Hi guys. I need your help please

Warning: Attempt to present <UINavigationController: 0x7c284400> on <PBRevealViewController: 0x7c266200> whose view is not in the window hierarchy!

Having that issue

**Comment by iDevelopper** [comment]
It seems that is not relative to the framework, but can you elaborate? What is your code?

**Comment by turganbekuly** [comment]
So I'm trying to push MainPageViewController when I click to LogIn button. It performs segue and then quit back to LoginViewController and gives that error (only for iPhone 5) (with iPhone 5s and higher everything works just fine)

Warning: Attempt to present <UINavigationController: 0x7c284400> on <PBRevealViewController: 0x7c266200> whose view is not in the window hierarchy!

**Comment by iDevelopper** [comment]
Can you provide an example reproducing this error? In my opinion, there is an architectural problem in your project.
