### ISSUE TITLE
How to fade FrontViewcontroller on swipe or Pangesture.

### ISSUE THREAD

**Issue by shashi-kiwi** [iDevelopper/PBRevealViewController#84]
Hi @iDevelopper 
 I want to set alpha to 0.3 of FrontViewController or say MainView Controller on pan gesture or Swipe right but slowly and similarly when coming back to Front VC. Currently Coming back is  not as per Pan gesture it hides Left Menu instantly.
Please suggest what to do?
Thanks inAdvance.

**Comment by iDevelopper** [comment]
Hello,

All this can be seen in the demo projects (see ExampleWithSwiftLibrary example).
Use the delegate methods, assuming you are in a PBRevealViewController subclass:
```swift
    func revealController(_ revealController: PBRevealViewController, willShowLeft viewController: UIViewController)
    {
        revealController.panGestureRecognizer?.cancelsTouchesInView = true
        mainViewController?.view.isUserInteractionEnabled = false
        mainViewController?.view.alpha = 0.3
    }

    func revealController(_ revealController: PBRevealViewController, willHideLeft viewController: UIViewController)
    {
        revealController.panGestureRecognizer?.cancelsTouchesInView = true
        mainViewController?.view.isUserInteractionEnabled = true
        mainViewController?.view.alpha = 1
    }

    func revealControllerPanGestureMoved(_ revealController: PBRevealViewController, direction: PBRevealControllerPanDirection)
    {
        if let pgr = panGestureRecognizer, let main = mainViewController {
            let progress = min(abs(pgr.translation(in: view).x / leftViewRevealWidth), 1)
            print("Progress: \(progress)")
            let alpha = max(1.0 - progress, 0.3)
            print("Alpha: \(alpha)")
            main.view.alpha = alpha
        }
    }
```
For the animation timing and duration, use the properties:
`leftToggleAnimationDuration`, `leftToggleSpringDampingRatio`, `leftToggleSpringVelocity`, `swipeVelocity`. You can set `swipeVelocity` to 1500 for example to reduce the sensibility.
